######  <center>Numpy - linear algebra</center>

In [6]:
# one dimensional -> vectors
# two dimensional ->  matrices

In [7]:
import numpy as np

In [14]:
lst = [1,2,3]
lst

[1, 2, 3]

In [15]:
array  = np.array(lst)

In [16]:
array

array([1, 2, 3])

In [17]:
lst_of_list = [[1,2,3],[4,5,6],[7,8,9]]
lst_of_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [19]:
array_3d = np.array(lst_of_list)
array_3d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(0,1.1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [33]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [34]:
np.zeros((5,5), int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [35]:
np.zeros((2,3),int)

array([[0, 0, 0],
       [0, 0, 0]])

In [37]:
np.ones((2,3), int)

array([[1, 1, 1],
       [1, 1, 1]])

In [51]:
np.linspace(1,2,10,dtype=int,retstep=True,endpoint=False)

(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]), 0.1)

In [52]:
np.eye(5)   # Identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [62]:
np.eye(3,k= 1, dtype= int)  # k value +ve, -ve, 0 -> upper triangle, lower triangle, diagonal

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [66]:
np.random.rand(2)

array([0.13433175, 0.21097705])

In [68]:
np.random.rand(2,3)

array([[0.00758252, 0.96338655, 0.14587754],
       [0.03056062, 0.26817936, 0.81877357]])

In [72]:
np.random.randn(3)   # gives values of normal distribution   (mean 0 and variance 1)

array([ 0.27349065, -1.40405455,  0.48552348])

In [74]:
np.random.randint(1,100,5)

array([38, 78, 42,  6, 17])

In [77]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [78]:
rand_array =  np.random.randint(0,100,10)
rand_array

array([69, 51, 88, 19, 84,  2, 52,  8, 71, 63])

In [84]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [86]:
rand_array.max()

88

In [87]:
rand_array.min()

2

In [88]:
rand_array.argmax()

2

In [97]:
rand_array

array([69, 51, 88, 19, 84,  2, 52,  8, 71, 63])

In [98]:
print("Min position -> ",rand_array.argmin(),", " ,"Min value ->",rand_array.min())

Min position ->  5 ,  Min value -> 2


In [100]:
arr.shape

(25,)

In [105]:
arr = arr.reshape(5,5)
arr.shape

(5, 5)

In [106]:
arr.dtype

dtype('int32')

In [107]:
from numpy.random import randint

In [111]:
randint(2,101)

46

###### <center>Indexing and selection in NumPy</center>

In [114]:
arr.shape

(5, 5)

In [115]:
arr = arr.reshape(25)

In [116]:
arr.shape

(25,)

In [117]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [121]:
arr[24]

24

In [122]:
arr[1:10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [127]:
arr[:5] =1
arr

array([ 1,  1,  1,  1,  1,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [129]:
arr_ten = arr[1:11]
arr_ten

array([ 1,  1,  1,  1,  5,  6,  7,  8,  9, 10])

In [154]:
arr_copy = arr_ten.copy()
arr_copy

array([ 1,  1,  1,  1,  5,  6,  7,  8,  9, 10])

In [155]:
arr_copy[5:8][1] = 3333
arr_copy

array([   1,    1,    1,    1,    5,    6, 3333,    8,    9,   10])

In [158]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d.shape)
arr_2d

(3, 3)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [169]:
arr_2d[0][1]

2

In [170]:
arr_2d[0,1]

2

In [172]:
arr_2d[:,0]

array([1, 4, 7])

In [173]:
arr_2d[:,0] + 5

array([ 6,  9, 12])

In [174]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [177]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [179]:
arr_append = np.arange(5)
arr_append

array([0, 1, 2, 3, 4])

In [188]:
np.append(arr_append,arr_append)

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [189]:
arr

array([ 1,  1,  1,  1,  1,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [190]:
test_arr = arr[3:10]
test_arr

array([1, 1, 5, 6, 7, 8, 9])

In [191]:
test_arr > 5

array([False, False, False,  True,  True,  True,  True])

In [193]:
bool_arr = test_arr > 5
bool_arr

array([False, False, False,  True,  True,  True,  True])

In [197]:
print("test_arr", test_arr)
test_arr[bool_arr]


test_arr [1 1 5 6 7 8 9]


array([6, 7, 8, 9])

In [200]:
test_arr[test_arr > 6]

array([7, 8, 9])

###### <center> Operations in NumPy </center>

In [202]:
arr_op = np.arange(11)
arr_op

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [203]:
arr_op + arr_op

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [204]:
arr_op - arr_op

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [205]:
arr_op * arr_op

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [206]:
arr_op + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [207]:
arr_op * 10

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [209]:
arr_op /arr_op

C:\Users\Akash\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [211]:
1/arr_op

C:\Users\Akash\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [213]:
arr_op ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [214]:
np.sqrt(arr_op)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [215]:
np.exp(arr_op)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [217]:
arr_op.argmax()

10

In [218]:
np.max(arr_op)

10

In [267]:
np.sin(arr_op)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])